### ISSUE TITLE
Readme assets

### ISSUE THREAD

**Issue by thekaganugur** [kgnugur/alfred-workflows#1]
![Kapture 2019-09-29 at 14 14 31-min](https://user-images.githubusercontent.com/28161197/65831745-d61a6700-e2c5-11e9-9f49-05b8b95ad9e9.gif)

**Comment by kgnugur** [comment]
https://user-images.githubusercontent.com/28161197/103171047-1aded600-485a-11eb-8e4e-35b06a068894.mov

**Comment by thekaganugur** [comment]
https://user-images.githubusercontent.com/28161197/103171270-fbe14380-485b-11eb-9aa2-c076a858e3b5.mov
